apiVersion: v1
kind: Service
metadata:
  name: k8-the-straightforward-way-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    name: k8-the-straightforward-way
